# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: midas
  region: us-east-2

vpc: 
  cidr: 12.10.0.0/16 

managedNodeGroups:
  - name: midas
    instanceType: m5.xlarge
    desiredCapacity: 4
    minSize: 4 
    maxSize: 4
    volumeSize: 100
    volumeType: gp2
    labels:
      nodegroup-type: midas